services:
  identity:
    build:
      context: .
      dockerfile: ./apps/identity/Dockerfile
      target: development
    command: pnpm start:dev identity
    ports:
      - '3000:3000'
    env_file:
      - ./apps/identity/.env
    volumes:
      - '.:/usr/src/app'
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm start:dev payments
    ports:
      - '3001:3001'
    env_file:
      - ./apps/payments/.env
    volumes:
      - '.:/usr/src/app'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'